# Generated by Django 5.2.4 on 2026-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch'), ('hotfix', 'Hotfix')], default='minor', max_length=16)),
                ('released_at', models.DateField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
    ]
