# Generated by Django 5.2.4 on 2026-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_announcement_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementlog',
            name='audience',
            field=models.CharField(choices=[('test', 'Test'), ('all', 'All Users'), ('specific', 'Specific Emails')], max_length=8),
        ),
        migrations.AlterField(
            model_name='announcementlog',
            name='test_recipient',
            field=models.TextField(blank=True, help_text='Email address(es) used for test or specific sends'),
        ),
    ]
