# Generated by Django 5.2.4 on 2025-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_habitlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
