# Generated by Django 5.2.4 on 2026-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_dashboard_revamp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timelineevent',
            new_name='board_timel_user_id_30b189_idx',
            old_name='board_timel_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='timelineevent',
            new_name='board_timel_user_id_ca1e00_idx',
            old_name='board_timel_user_ty_idx',
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('completed', 'Completed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='clock_format',
            field=models.CharField(choices=[('12h', 'Twelve'), ('24h', 'Twenty Four')], default='12h', max_length=4),
        ),
    ]
