# Generated by Django 5.2.4 on 2026-03-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_migrate_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineentry',
            name='is_active',
        ),
    ]
