# Generated by Django 5.2.4 on 2026-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_routineentry_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='focus_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
