# Generated by Django 5.2.4 on 2026-04-26 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_add_focus_minutes_to_dailydata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountabilitypartner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='accountabilitypartner',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accountabilitypartner',
            name='status',
            field=models.CharField(choices=[('request-sent', 'Request Sent'), ('active', 'Active'), ('inactive', 'Inactive')], default='request-sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountabilitypartner',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountability_partners', to='board.habit'),
        ),
        migrations.AlterField(
            model_name='accountabilitypartner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountability_partnerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('habit', 'Habit'), ('todo', 'Todo'), ('routine', 'Routine'), ('sleep_tracker', 'Sleep Tracker'), ('journal', 'Journal'), ('text', 'Text'), ('meeting', 'Meeting'), ('friend_request', 'Friend Request'), ('accountability_invite', 'Accountability Invite'), ('accountability_habit', 'Accountability Habit')], max_length=32),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
