# Generated by Django 5.2.4 on 2026-04-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_default_dark_theme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskgroup',
            unique_together=set(),
        ),
    ]
