# Generated by Django 5.2.4 on 2026-05-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_feedback_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'google_email')},
            },
        ),
        migrations.CreateModel(
            name='LinkedCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sync_habits', models.BooleanField(default=False)),
                ('sync_tasks', models.BooleanField(default=False)),
                ('webhook_channel_id', models.CharField(blank=True, max_length=255)),
                ('webhook_resource_id', models.CharField(blank=True, max_length=255)),
                ('webhook_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='board.googlecalendartoken')),
            ],
            options={
                'unique_together': {('token', 'calendar_id')},
            },
        ),
    ]
